DROP TABLE IF EXISTS SALON;

CREATE TABLE SALON (
    id INTEGER PRIMARY KEY,
    nombre TEXT NOT NULL,
    apellido TEXT NOT NULL,
    calificacion TEXT NOT NULL,
    ciudad TEXT NOT NULL,
    pais TEXT NOT NULL,
    tesoro TEXT NOT NULL
);